### ISSUE TITLE
Can't update Homebridge-Config-UI-X

### ISSUE THREAD

**Issue by stubbz00** [homebridge/homebridge#3393]
### Current Situation

I am running oznu/homebridge:ubuntu on a Firewalla based on the Firewalla guides.  

**docker-compose.yaml**
```
version: '2'
services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8582
      - TZ=America/New_York
    volumes:
      - '/data/homebridge:/homebridge'
```

A few weeks ago I updated from 4.50.1 to 4.50.2.  Now when I try and update to the latest version, 4.50.4, the install is successful and shows as updated in the UI, but if I restart the docker Homebridge-Config-UI-X reverts back to 4.50.2.

I've tried the following a fix I found on the Homebridge-Config-UI-X issues page:
https://github.com/homebridge/homebridge-config-ui-x/issues/1457#issuecomment-1534886496
```
sudo hb-shell
/opt/homebridge/lib/node_modules/homebridge-config-ui-x/upgrade-install.sh 4.50.1 /opt/homebridge
exit
sudo hb-service restart
sudo hb-service logs
```
I also tried to prune the docker image and download the image again, but didn't resolve the issue.

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

- OS: Ubuntu 20.04 / Firewalla Purple
- Software: Homebridge 1.6.1
- Node: 18.13.0
- npm: 8.19.3

### Process Supervisor

hb-service
