### ISSUE TITLE
Update TrueNAS Scale wiki page

### ISSUE THREAD

**Issue by maxileith** [homebridge/homebridge#3736]
### Proposed Change

The TrueNAS Scale installation page does not apply to the latest TrueNAS Scale version (ElectricEel-24.10.0) and people in the TrueNAS forum and on reddit are having problems to run homebridge. TrueNAS Scale apps do not longer run on k8s but on docker. Gladly TrueNAS Scale supports docker-compose.yaml files now.

However, it is very easy to get homebridge up and running again. Creating an app with the following docker-compose.yaml file will be sufficient.

* `192.168.0.0/24` is the subnet of the LAN
* `192.168.0.1` is the gateway
* `192.168.0.12` is an unocuppied IP
* `enp3s0` is the network adapter that should be used

```yaml
networks:
  homebridge_net:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      config:
        - gateway: 192.168.0.1
          subnet: 192.168.0.0/24
services:
  homebridge:
    container_name: homebridge
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 3072M
    image: homebridge/homebridge:latest
    networks:
      homebridge_net:
        ipv4_address: 192.168.0.12
    restart: unless-stopped
    volumes:
      - /mnt/App Pool/homebridge:/homebridge
```

After creating the app, homebridge will be available at `http://192.168.0.12:8581`.

### Wiki Page Link

https://github.com/homebridge/docker-homebridge/wiki/Homebridge-on-TrueNAS-Scale
